---
- name: Setup nieuwe laptop
  hosts: localhost
  vars_prompt:
    - name: user_role
      prompt: "Wat is je rol? (developer/sales)"
      private: no

    - name: dock_changes
      prompt: "Zal ik het dock bewerken? (y/n)"
      private: no

  tasks:
    - name: Verplaats Dock naar links
      osx_defaults:
        domain: com.apple.dock
        key: orientation
        value: left
      become: true
      when: dock_changes == 'y'
    - name: Stel vertraging van weergave Dock in
      osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        value: 0
      become: true
      when: dock_changes == 'y'
    - name: Install casks
      become: no
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - whatsapp
        - zoom
        - google-chrome
        #  SALES apps
    #    - name: Install sales casks
    #      when: user_role == 'sales'
    #      become: no
    #      homebrew_cask:
    #        name: "{{ item }}"
    #        state: present
    #      loop:
    #        - sample
    - name: Install dev casks
      when: user_role == 'developer'
      become: no
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - docker
    #        - 1password
    #        - alfred
    #        - amazon-chime
    #        - boop
    #        - curseforge
    #        - db-browser-for-sqlite
    #        - dotnet
    #        - dropzone
    #        - figma
    #        - firefox
    #        - iterm2
    #        - jetbrains-toolbox
    #        - macdown
    #        - opera
    #        - opera-gx
    #        - postman
    #        - rar
    #        - sequel-pro
    #        - sidequest
    #        - skype
    #        - slack
    #        - spectacle
    #        - spotify
    #        - sublime-text
    #        - tableplus
    #        - teamviewer
    #        - tower
    #        - utm
    #        - visual-studio-code
    #        - vlc
#    - name: Run Jetbrains Toolbox
#      command: '/Users/joeriabbo/Applications/JetBrains Toolbox.app/Contents/MacOS/jetbrains-toolbox'
#      when: user_role == 'developer'
#
#    - name: Installeer PhpStorm
#      command: "~/Applications/JetBrains Toolbox/JetBrains Toolbox.app/Contents/MacOS/jetbrains-toolbox --jetbrains-toolbox --install=phpstorm"
#      when: user_role == 'developer'
#
#    - name: Installeer GoLand
#      command: "~/Applications/JetBrains Toolbox/JetBrains Toolbox.app/Contents/MacOS/jetbrains-toolbox --jetbrains-toolbox --install=goland"
#      when: user_role == 'developer'
#
#    - name: Installeer WebStorm
#      command: "~/Applications/JetBrains Toolbox/JetBrains Toolbox.app/Contents/MacOS/jetbrains-toolbox --jetbrains-toolbox --install=webstorm"
#      when: user_role == 'developer'
#
#    - name: Installeer IntelliJ IDEA Ultimate
#      command: "~/Applications/JetBrains Toolbox/JetBrains Toolbox.app/Contents/MacOS/jetbrains-toolbox --jetbrains-toolbox --install=ideaIC"
#      when: user_role == 'developer'
#
#    - name: Installeer Rider
#      command: "~/Applications/JetBrains Toolbox/JetBrains Toolbox.app/Contents/MacOS/jetbrains-toolbox --jetbrains-toolbox --install=rider"
#      when: user_role == 'developer'
#
#    - name: Install PycCharm Professional Edition
#      import_tasks: editors/pycharm.yaml
#      when: user_role == 'developer'

    - name: Install Language stuff
      import_tasks: install-languages.yaml
      when: user_role == 'developer'